-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Player"
(
    "Full_name" character varying NOT NULL,
    "Position" character varying NOT NULL,
    "Player_ID" integer NOT NULL,
    "Team_ID" integer NOT NULL,
    PRIMARY KEY ("Player_ID")
);

CREATE TABLE IF NOT EXISTS public."Match"
(
    "Stadium" character varying NOT NULL,
    "Match_Date" date NOT NULL,
    "Match_ID" integer NOT NULL,
    PRIMARY KEY ("Match_ID")
);

CREATE TABLE IF NOT EXISTS public."Team"
(
    "Team_ID" integer NOT NULL,
    "Emblem" text NOT NULL,
    "Name" character varying NOT NULL,
    PRIMARY KEY ("Team_ID")
);

CREATE TABLE IF NOT EXISTS public."Team_Match"
(
    "Team_ID" integer NOT NULL,
    "Match_ID" integer NOT NULL
);
END;