-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Player"
(
    "Full_name" character varying NOT NULL,
    "Position" character varying NOT NULL,
    "Player_ID" integer NOT NULL,
    "Team_ID" integer,
    PRIMARY KEY ("Player_ID")
);

CREATE TABLE IF NOT EXISTS public."Match"
(
    "Stadium" character varying NOT NULL,
    "Match_Date" date NOT NULL,
    "Match_ID" integer NOT NULL,
    PRIMARY KEY ("Match_ID")
);

CREATE TABLE IF NOT EXISTS public."Team"
(
    "Team_ID" integer NOT NULL,
    "Emblem" text NOT NULL,
    "Name" character varying NOT NULL,
    PRIMARY KEY ("Team_ID")
);

CREATE TABLE IF NOT EXISTS public."Match_Team"
(
    "Match_Match_ID" integer NOT NULL,
    "Team_Team_ID" integer NOT NULL,
    PRIMARY KEY ("Match_Match_ID", "Team_Team_ID")
);

ALTER TABLE IF EXISTS public."Player"
    ADD FOREIGN KEY ("Team_ID")
    REFERENCES public."Team" ("Team_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Match_Team"
    ADD FOREIGN KEY ("Match_Match_ID")
    REFERENCES public."Match" ("Match_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Match_Team"
    ADD FOREIGN KEY ("Team_Team_ID")
    REFERENCES public."Team" ("Team_ID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;